resources:
  - name: mac10_bits_ecr_cli
    type: cliConfig
    integration: ecr_bits_push
    pointer:
      region: us-east-1

  - name: mac10_dh_cli
    type: cliConfig
    integration: ric03uec-dockerhub

jobs:
  - name: reqProc_x86_64_macOS_10_12_prep
    type: runSh
    triggerMode: parallel
    dependencyMode: strict
    runtime:
      architecture: x86_64
      os: macOS_10.12
      container: false
    steps:
      - IN: mac10_bits_ecr_cli
        scopes:
          - ecr
        switch: off
      - IN: mac10_dh_cli
        switch: off
      - IN: reqProc_repo
      - IN: reqExec_x86_64_Ubuntu_14_04_pack
      - IN: reqExec_x86_64_Ubuntu_16_04_pack
      - IN: package_reqExec_x86_64_CentOS_7
      - IN: package_reqExec_x86_64_macOS_10_12
      - IN: reqExec_aarch64_Ubuntu_16_04_pack
      - IN: execTemplates_repo
      - IN: microbase_img
      - TASK:
          script:
            - pushd $(shipctl get_resource_state "reqProc_repo")
            - ./build.sh x86_64 macOS_10.12 drydock m10reqproc
            - popd
